### ISSUE TITLE
Dealing with binary string

### ISSUE THREAD

**Issue by drupol** [thephpleague/uri-query-parser#6]
Hello,

I'm wondering how such query strings should be handled:

```php
$query = 'a%00b=c';
```

When I extract the parameters, I get a binary string, which is obviously invalid.

Maybe we should add a check to make sure it returns a valid string in those cases ?

I added the following test:

```php
            [
                'query' => 'a%00b=c',
                'expected' => [
                    'a' => 'c',
                ]
            ]
```

And the output is:

```
> phpunit --coverage-text
PHPUnit 8.5.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.31 with Xdebug 2.9.5
Configuration: /home/pol/dev/git/uri-query-parser/phpunit.xml

..................F..........................................     61 / 61 (100%)

Time: 310 ms, Memory: 8.00 MB

There was 1 failure:

1) LeagueTest\Uri\QueryStringTest::testExtractQuery with data set #13 ('a%00b=c', array('c'))
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &0 (
-    'a' => 'c'
+    Binary String: 0x610062 => 'c'
 )

/home/pol/dev/git/uri-query-parser/tests/QueryStringTest.php:64

FAILURES!
Tests: 61, Assertions: 76, Failures: 1.

Generating code coverage report in Clover XML format ... done [45 ms]

Generating code coverage report in HTML format ... done [36 ms]

```

WDYT ?

**Comment by nyamsprod** [comment]
@drupol thanks for the report. I had not taken binary string into account. So kudo on spotting that one out. 👍 

I believe for the correct behaviour you should:

- first look at [WHATWG documentation](https://url.spec.whatwg.org/#interface-urlsearchparams) 

- tests the following code in Chrome and Firefox to check if the result are the same.

```javascript
    const queryString = new URLSearchParams('?a%00b=c');
    for (const [key, value] of queryString) {
        console.log('key =', key, 'value = ', value);
    }
```

- look into [the webplatform test suite](https://github.com/web-platform-tests/wpt/tree/master/url) to see if some tests do cover this example. Then  we will be able to correctly tackle the behaviour as the current one is indeed buggy.

After which we can document and update the expected behaviour. (Extra point would be to open an issue on the WHATWG source code if the behaviour is not expected/described).

Also once this is done I'll update (or you can the [URI component package](https://github.com/thephpleague/uri-components/) as the current package is only on maintenance mode and most of the code is now written against the component package.

**Comment by drupol** [comment]
Thanks!

Here's the result in Firefox:

![image](https://user-images.githubusercontent.com/252042/84883793-47d35480-b091-11ea-9c4d-681879a65278.png)
